# Generated by Django 4.1.7 on 2023-08-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="inventory.inventorylanguage",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="inventory.inventorytype",
            ),
        ),
    ]
